# Generated by Django 6.0.7 on 2026-07-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, unique=True)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
